// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@pageinsighttool.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analyze": {
            "get": {
                "description": "Analyzes a web page and extracts HTML version, title, headings, links, login forms, and CSR detection information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Analyze a web page",
                "parameters": [
                    {
                        "type": "string",
                        "example": "https://example.com",
                        "description": "URL of the web page to analyze",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AnalysisResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid URL",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "422": {
                        "description": "HTML parsing error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API including version, environment, and server status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.HealthResponse": {
            "type": "object",
            "properties": {
                "build_date": {
                    "type": "string",
                    "example": "2025-10-29T22:00:00Z"
                },
                "environment": {
                    "type": "string",
                    "example": "development"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-10-29T22:00:00Z"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "models.AnalysisResponse": {
            "type": "object",
            "properties": {
                "analysis_time_ms": {
                    "type": "integer",
                    "example": 150
                },
                "has_login_form": {
                    "type": "boolean",
                    "example": true
                },
                "headings": {
                    "$ref": "#/definitions/models.Headings"
                },
                "html_version": {
                    "type": "string",
                    "example": "HTML5"
                },
                "links": {
                    "$ref": "#/definitions/models.Links"
                },
                "page_title": {
                    "type": "string",
                    "example": "Google"
                }
            }
        },
        "models.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string",
                    "example": "Invalid URL"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "example": "INVALID_URL"
                }
            }
        },
        "models.Headings": {
            "type": "object",
            "properties": {
                "h1": {
                    "type": "integer",
                    "example": 10
                },
                "h2": {
                    "type": "integer",
                    "example": 20
                },
                "h3": {
                    "type": "integer",
                    "example": 30
                },
                "h4": {
                    "type": "integer",
                    "example": 40
                },
                "h5": {
                    "type": "integer",
                    "example": 50
                },
                "h6": {
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "models.Links": {
            "type": "object",
            "properties": {
                "external": {
                    "type": "integer",
                    "example": 20
                },
                "inaccessible": {
                    "type": "integer",
                    "example": 30
                },
                "internal": {
                    "type": "integer",
                    "example": 10
                }
            }
        }
    },
    "tags": [
        {
            "description": "Web page analysis endpoints",
            "name": "Analysis"
        },
        {
            "description": "Health check and monitoring endpoints",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Page Insight Tool API",
	Description:      "A production-grade web page analysis tool that analyzes HTML pages and extracts insights including headings, links, login forms, and more.\nSupports both static HTML analysis and Client-Side Rendered (CSR) website detection.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}
